plugins: preview paste searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount help charmap quickbars emoticons
paste_retain_style_properties: 'color font-size'
editimage_cors_hosts:
  - picsum.photos
menubar: file edit view insert format tools table help
toolbar: undo redo | bold italic underline strikethrough blockquote | fontfamily fontsize blocks | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl
toolbar_sticky_offset: 102
autosave_ask_before_unload: true
autosave_interval: 30s
autosave_prefix: '{path}{query}-{id}-'
autosave_restore_when_empty: false
autosave_retention: 2m
image_advtab: true
template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]'
template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]'
height: 600
image_caption: true
quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote quickimage quicktable'
noneditable_class: 'mceNonEditable'
toolbar_mode: 'sliding'
contextmenu: 'link image table'
# extended_valid_elements: 'a[href|target=_blank]'
images_upload_url: '/account/tinymce_pictures'
relative_urls: false
content_css: 'tailwind.css'
invalid_styles:
    'p': 'background-color'
    'h2': 'background-color'
    'h3': 'background-color'
